name = "sodekputravpn"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.133.223.50:2096"
UUID = "affc349c-179d-4151-84f4-f556e6f3076a"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
